### ISSUE TITLE
Is it possible with Quick Apps to write in Russian

### ISSUE THREAD

**Issue by ghost** [quickapps/cms#113]
Hello Developers,

I have Quick Apps installed on a Russian blog, and have created the first article and have to say that publishing is not working. It is up to the language because I write the article title in Russian.

When I look at the Error.log following appears!

```
2015-05-31 16:27:12 Error: [PDOException] SQLSTATE[HY000]: General error:  1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and  (utf8_general_ci,COERCIBLE) for operation 'like'
Request URL: /cms/quickapps/ru/admin/content/manage/add/article
Stack Trace:
#0 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Database/Connection.php(275): Cake\Database\Statement\MysqlStatement->execute()
#2 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Database/Query.php(175): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#3 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/ORM/Query.php(657): Cake\Database\Query->execute()
#4 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php(218): Cake\ORM\Query->_execute()
#5 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/ORM/Query.php(608): Cake\ORM\Query->_all()
#6 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/quickapps/cms/plugins/CMS/src/Model/Behavior/SluggableBehavior.php(157): Cake\ORM\Query->all()
#7 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/quickapps/cms/plugins/CMS/src/Model/Behavior/SluggableBehavior.php(103): CMS\Model\Behavior\SluggableBehavior->_slug(' \xD0\xAF \xD1\x83\xD1\x81\xD1\x82\xD0\xB0\xD0\xBD\xD0...', Object(Content\Model\Entity\Content))
#8 /www/htdocs/w011cb04/cms/quickapps/vendor/cakephp/cakephp/src/Event/EventManager.php(385): CMS\Model\Behavior\SluggableBehavior->beforeSave(Object(Cake\Event\Event), Object(Content\Model\Entity\Content), Object(ArrayObject))
#9 /www/htdocs/w011cb04/cms/quickapps/vendor/cakephp/cakephp/src/Event/EventManager.php(351): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#10 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Event/EventManagerTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#11 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/ORM/Table.php(1361): Cake\ORM\Table->dispatchEvent('Model.beforeSav...', Array)
#12 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/ORM/Table.php(1313): Cake\ORM\Table->_processSave(Object(Content\Model\Entity\Content), Object(ArrayObject))
#13 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Database/Connection.php(562): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#14 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/ORM/Table.php(1314): Cake\Database\Connection->transactional(Object(Closure))
#15 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/quickapps/cms/plugins/Content/src/Controller/Admin/ManageController.php(123): Cake\ORM\Table->save(Object(Content\Model\Entity\Content))
#16 [internal function]: Content\Controller\Admin\ManageController->add('article')
#17 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Controller/Controller.php(412): call_user_func_array(Array, Array)
#18 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#19 /www/htdocs/w011cb04/cms/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(Content\Controller\Admin\ManageController))
#20 /www/htdocs/w011cb04/cms/quickapps/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#21 {main}
```

Whether you can help me here? Thanks in advance

P.S. I have set in the backend in the Configuration and then in the User Profile The Russian language. The language has not changed in the backend. How can it be?

**Comment by quickapps** [comment]
Seem to be an issue with your database collation when generating contents slugs with special chars, `utf8_unicode_ci` is preferable, but I think you are using `latin1_swedish_ci` instead.

I'll take a look to this issue, Slugs generator should work whatever the collation is used for DB.

QACMS is currently available only in English and Spanish. QACMS lets you define any language for your site regardless if a translation package exists or not, that is why interfaces may not be fully translated because of incomplete/missing translation packages.

Thanks for reporting this one!

**EDIT:**

Could you please check that your tables were created using `utf8_unicode_ci` [during installation process](https://github.com/quickapps/cms/blob/2.0/plugins/Installer/config/fixture/ContentsFixture.php#L93)?. You can check this using phpMyAdmin or similar. (see image below)
![captura](https://cloud.githubusercontent.com/assets/1129842/7903487/18d60896-07de-11e5-9d2a-3d7a0155af91.PNG)

**Comment by ghost** [comment]
Many Thanks! Yes, I wanted to give it a try but since you say that QA yet available in English and Spanish, it is fine and I have already a German QA blog. That's enough for me. If added wide tere languages one day, I'll try it, at least I still had Russian interests. German and English are also fine. Thank you!
