### ISSUE TITLE
Translation packages table missing: [MissingTableException] Table qa_packages for model Package was not found in datasource default.

### ISSUE THREAD

**Issue by mikeful** [quickapps/cms#13]
Installed v1.0RC2 from GitHub zipball, got problem running installer and installed database manually. Everything seems to work fine except I can't find "qa_packages" table creation in database schema file.

Full error from log:

```
2012-01-07 10:57:06 Error: [MissingTableException] Table qa_packages for model Package was not found in datasource default.
#0 C:\<path to QuickApps>\quickapps\app\Cake\Model\Model.php(3334): Model->setSource('packages')
#1 C:\<path to QuickApps>\quickapps\app\Cake\Model\Model.php(1277): Model->getDataSource()
#2 C:\<path to QuickApps>\quickapps\app\Cake\Model\Model.php(1363): Model->schema()
#3 C:\<path to QuickApps>\quickapps\app\Model\Behavior\WhoDidItBehavior.php(49): Model->hasField('created_by')
#4 C:\<path to QuickApps>\quickapps\app\Cake\Model\BehaviorCollection.php(145): WhoDidItBehavior->setup(Object(LocaleAppModel), Array)
#5 C:\<path to QuickApps>\quickapps\app\Cake\Model\BehaviorCollection.php(68): BehaviorCollection->load('WhoDidIt', Array)
#6 C:\<path to QuickApps>\quickapps\app\Cake\Model\Model.php(723): BehaviorCollection->init('Package', Array)
#7 C:\<path to QuickApps>\quickapps\app\Model\AppModel.php(23): Model->__construct(Array, NULL, NULL)
#8 C:\<path to QuickApps>\quickapps\app\Cake\Utility\ClassRegistry.php(176): AppModel->__construct(Array)
#9 C:\<path to QuickApps>\quickapps\app\Cake\View\Helper\FormHelper.php(151): ClassRegistry::init(Array)
#10 C:\<path to QuickApps>\quickapps\app\Cake\View\Helper\FormHelper.php(337): FormHelper->_getModel('Package')
#11 C:\<path to QuickApps>\quickapps\app\View\Helper\QaFormHelper.php(60): FormHelper->create('Package', Array)
#12 C:\<path to QuickApps>\quickapps\app\Plugin\Locale\View\Packages\admin_index.ctp(1): QaFormHelper->create('Package', Array)
#13 C:\<path to QuickApps>\quickapps\app\Cake\View\View.php(869): include('C:\<path to QuickApps>...')
#14 C:\<path to QuickApps>\quickapps\app\Cake\View\View.php(833): View->_evaluate('C:\<path to QuickApps>...', Array)
#15 C:\<path to QuickApps>\quickapps\app\Cake\View\View.php(444): View->_render('C:\<path to QuickApps>...')
#16 C:\<path to QuickApps>\quickapps\app\Cake\Controller\Controller.php(933): View->render(NULL, NULL)
#17 C:\<path to QuickApps>\quickapps\app\Cake\Routing\Dispatcher.php(111): Controller->render()
#18 C:\<path to QuickApps>\quickapps\app\Cake\Routing\Dispatcher.php(86): Dispatcher->_invoke(Object(PackagesController), Object(CakeRequest), Object(CakeResponse))
#19 C:\<path to QuickApps>\quickapps\webroot\index.php(47): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
```

**Comment by quickapps** [comment]
Try to install the lastest version available, lot of changes and new features were added since RC2.
https://github.com/QuickAppsCMS/QuickApps-CMS/zipball/1.0

I'll fix the Form helper issue.....new model-guessing feature of cakephp 2

P.S.: "got problem running installer" Would you describe the problems you got? So I can try to fix it.

## 

Thanks!,
Chris

**Comment by mikeful** [comment]
Link gives me file "QuickAppsCMS-QuickApps-CMS-1.0-RC2-66-gcc03062.zip" which I'm currently using.

Installer problem: I can't remember exact error but it related to extracting files from downloaded zip package when using Quick-Installer method. Downloaded file was only ~20 kB in size so this might be something wrong in my local environment.

**Comment by quickapps** [comment]
Oh! I see, you are using the quick-installer script.
It downloads the lastest package from github URL which is a secure protocol (https), this may cause some problems under certain enviroments that are not properly configured. That is why the "Github based installer" is the recommended installation process.
